### ISSUE TITLE
Addon Installation Problem and Fix

### ISSUE THREAD

**Issue by saltysausage** [BeamNG/Blender-JBeam-Editor#5]
When installing this addon I followed the exact procedure as shown in the pictures however when searching in addons for the Jbeam to enable it, it isnt there. To actually install it properly for some reason i had to extract the zip open C:\Users\*****\Downloads\Blender-JBeam-Editor-main\jbeam_editor - and copy jbeam_editor File directly into the blender directory -->C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons. I was then actually able to see it in addons and enable it. Bit of an odd issue and took me a while to solve but it works now :))

**Comment by Blenux** [comment]
You used the .zip to download the main repo (which is why you add to manually copy the addon from that to blender's addon folder), 

You should download only the .zip from the releases page.

![Screenshot_20230929_172302](https://github.com/BeamNG/Blender-JBeam-Editor/assets/25260650/86af3aed-32e7-4509-9120-1b57f1f489d1)


https://github.com/BeamNG/Blender-JBeam-Editor/releases/tag/v0.1.3
