### ISSUE TITLE
Unable to export to new JBeam file

### ISSUE THREAD

**Issue by ContenderEliminated** [BeamNG/Blender-JBeam-Editor#7]
**Addon version:** 0.1.4
**Blender version:** 3.6.5

Here is a JBeam structure I'd like to export:
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/36343808/688688c9-916e-4c6b-8360-42592b8a3f8c)

I want to be able to use this addon in place of thomatoes50's existing exporter addon (which doesn't allow for the naming of individual nodes), but can't yet do that as this current addon doesn't seem to support exporting brand-new (not imported) JBeams.

On the first export attempt, it produced an incomplete JBeam file containing only the nodes, which I have subsequently been unable to reproduce:
![image](https://github.com/BeamNG/Blender-JBeam-Editor/assets/36343808/f4fe39c8-ba6d-41df-bbda-28d38e905a9b)

Every time I try to export it after that, Blender throws the error `Imported JBeam file could not be found. Please do not move the imported file while using the JBeam Editor.`

**Comment by angelo234** [comment]
Yeah currently its only able to export nodes. The reason is in many cases, you can have beams/triangles referencing nodes that aren't part of the same JBeam part/file. So you really need the full vehicle in many cases to handle them. So that's why I haven't supported handling beams/triangles yet. Sorry about that. 

The "Imported JBeam file could not be found. Please do not move the imported file while using the JBeam Editor." means that you cannot move the imported/exported JBeam file. You need to work on it in one place.

**Comment by ContenderEliminated** [comment]
Thanks for the reply. Is a single-part export option planned where any beam or triangle referencing nodes not defined in the part is ignored?

**Comment by angelo234** [comment]
Hmm, I guess I could have a mode like that. But this would come after full vehicle importing since I'm working on that now :)
